## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *
from eudplib.core.eudfunc import EUDTraceLog, EUDTracedFunc, EUDTracedTypedFunc, EUDTracedMethod, EUDTracedTypedMethod
from eudplib.epscript.helper import _RELIMP, _TYGV, _TYSV, _TYLV, _CGFW, _ARR, _VARR, _SRET, _SV, _ATTW, _ARRW, _ATTC, _ARRC, _L2V, _LSH, _ALL
# (Line 1) var addr, ptrAddr, patternAddr, num;
addr, ptrAddr, patternAddr, num = EUDCreateVariables(4)
# (Line 2) var pChat;//, chat
pChat = EUDVariable()
# (Line 4) const nums_ = PVariable();
nums_ = _CGFW(lambda: [PVariable()], 1)[0]
# (Line 5) const patternAction_ = PVariable();
patternAction_ = _CGFW(lambda: [PVariable()], 1)[0]
# (Line 6) const chatAction_ = PVariable();
chatAction_ = _CGFW(lambda: [PVariable()], 1)[0]
# (Line 7) const pattern_len = 13;
pattern_len = _CGFW(lambda: [13], 1)[0]
# (Line 10) EUDRegisterObjectToNamespace("addr", addr);
EUDRegisterObjectToNamespace("addr", addr)
# (Line 11) EUDRegisterObjectToNamespace("ptrAddr", ptrAddr);
EUDRegisterObjectToNamespace("ptrAddr", ptrAddr)
# (Line 12) EUDRegisterObjectToNamespace("patternAddr", patternAddr);
EUDRegisterObjectToNamespace("patternAddr", patternAddr)
# (Line 13) EUDRegisterObjectToNamespace("num", num);
EUDRegisterObjectToNamespace("num", num)
# (Line 14) EUDRegisterObjectToNamespace("pChat", pChat);
EUDRegisterObjectToNamespace("pChat", pChat)
# (Line 15) EUDRegisterObjectToNamespace("nums_", nums_);
EUDRegisterObjectToNamespace("nums_", nums_)
# (Line 16) EUDRegisterObjectToNamespace("patternAction_", patternAction_);
EUDRegisterObjectToNamespace("patternAction_", patternAction_)
# (Line 17) EUDRegisterObjectToNamespace("chatAction_", chatAction_);
EUDRegisterObjectToNamespace("chatAction_", chatAction_)
# (Line 19) function run(){
@EUDFunc
def f_run():
    # (Line 20) if( patternAddr > 0 ){
    if EUDIf()(patternAddr <= 0, neg=True):
        # (Line 21) num = parse(ptrAddr + pattern_len)[[0]];
        num << (f_parse(ptrAddr + pattern_len)[0])
        # (Line 22) pChat = patternAddr;
        pChat << (patternAddr)
        # (Line 23) }
        # (Line 24) }
    EUDEndIf()
